query Contributors(
	$perPage: Int!
) {
	menuItems(
		first: $perPage
		where: {
			location: AUTHORS_WORK
		}
	) {
		nodes {
			id
			connectedObject {
				... on CoAuthor {
					posts(first: 1) {
						nodes {
							...ArticleTeaserParts
							authors:coAuthors {
								edges {
									node {
										...AuthorParts
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
