query EmailById(
	$id: ID!
) {
	email(
		id: $id
	) {
		...EmailParts
		disablePaywall
		blocks {
			innerHtml
			type
			tagName
			attributes {
				name
				value
			}
		}
		sendgridID
		emailLogoAd {
			alt
			src
			url
		}
		emailLists {
			nodes {
				...EmailListParts
			}
		}
	}
}
