query EmailsByList(
	$after: String = ""
	$perPage: Int = 10
	$slug: [String]!
	$tags: [String]
) {
	emailLists(
		where: {
			slug: $slug
		}
	) {
		nodes {
			...EmailListParts
			emails(
				after: $after
				first: $perPage
				where: {
					tagSlugIn: $tags
				}
			) {
				nodes {
					...EmailTeaserParts
				}
				pageInfo {
					endCursor
					hasNextPage
				}
			}
		}
	}
}
