query EmailListsBySlug(
	$slug: [String]!
) {
	emailLists(
		first: 1
		where: {
			slug: $slug
		}
	) {
		nodes {
			...EmailListParts
			emails(first: 1) {
				nodes {
					id
					emailId
				}
			}
		}
	}
}
