query EmailsByTag(
	$after: String = ""
	$perPage: Int = 10
	$slug: [String]
) {
	emails(
		after: $after
		first: $perPage
		where:{
			tagSlugIn: $slug
		}
	) {
		nodes {
			...EmailTeaserParts
			link
			emailLists {
				nodes {
				...EmailListParts
				}
			}
		}
		pageInfo {
			endCursor
			hasNextPage
		}
	}
}
