query LatestEmailByList(
    $slug: [String]
) {
  emailLists(where: {slug: $slug}) {
    nodes {
      id
      emails(first: 1) {
        nodes {
            html
            link
          ...EmailParts
        }
      }
    }
  }
}
