query LatestEmailByList(
	$perPage: Int = 1
	$slug: [String]!
) {
	emailLists(
		first: $perPage
		where: {
			slug: $slug
		}
	) {
		nodes {
			id
			emails(first: 1) {
				nodes {
					html
					...EmailTeaserParts
				}
			}
		}
	}
}
