query Collection(
	$id: Int!,
	$previewTime: Int,
	$previewToken: String,
) {
	collections(
		where: {
			id: $id,
			preview: { time: $previewTime, token: $previewToken }
		}
	) {
		nodes {
			...CollectionParts
		}
	}
}

