query EssentialsByArticle(
	$id: ID!
) {
	post(
		id: $id
	) {
		id
		essentials(first: 3) {
			nodes {
				...CollectionParts
			}
		}
		obsessions {
			nodes {
				...ObsessionParts
				essentials {
					nodes {
						...CollectionParts
					}
				}
			}
		}
		guides {
			nodes {
				...GuideParts
				essentials {
					nodes {
						...CollectionParts
					}
				}
			}
		}
	}
}
