query EssentialsByArticle(
	$id: ID!
) {
	post(
		id: $id
	) {
		id
		obsessions {
			nodes {
				...ObsessionParts
				essentials(
					first: 1
				) {
					nodes {
						...CollectionParts
					}
				}
			}
		}
	}
}
