fragment BulletinDataParts on BulletinData {	
    bulletin {
        campaign {
            attribution
            id
            logo
            logoLink
            name
            slug
        }
        clientTracking {
            article
            elsewhere
            logo
        }
        sponsor {
            attribution
            id
            logo
            logoLink
            name
            slug
        }
    }
}