fragment CollectionParts on Collection {
	id
	title
	dateGmt
	modifiedGmt
	slug
	featuredImage {
		...MediaParts
	}
	blocks {
		...BlockParts
		connections {
			... on Post {
				...ArticleTeaserParts
			}
			... on MediaItem {
				...MediaParts
			}
			... on Nug {
				...NugParts
			}
		}
	}
}
