fragment CollectionParts on Collection {
	id
	bulletin {
		campaign {
			id
			logo
			name
			slug
		}
		sponsor {
			attribution
			id
			slug
			name
		}
		clientTracking {
			article
			elsewhere
			logo
		}
	}
	collectionId
	title
	dateGmt
	modifiedGmt
	slug
	featuredImage {
		...MediaParts
	}
	blocks {
		...BlockParts
		connections {
			... on Post {
				...ArticleTeaserParts
			}
			... on MediaItem {
				...MediaParts
			}
			... on Nug {
				...NugParts
			}
		}
	}
}
