fragment EmailParts on Email {
	id
	authors:coAuthors {
		nodes{
		...AuthorParts
		}
	}
	dateGmt
	emailId
	featuredImage {
		...MediaParts
	}
	link
	segment
	socialImage {
		...MediaParts
	}
	seoTitle
	socialDescription
	socialTitle
	subject
	title
}
