fragment EmailParts on Email {
	...EmailTeaserParts
	disablePaywall
	blocks {
		...BlockParts
		connections {
        	... on Promotion {
				...PromotionParts
			}
		}
	}
	sendgridID
	emailLogoAd {
		alt
		src
		url
	}
}
