fragment EmailTeaserParts on Email {
	id
	dateGmt
	emailId
	featuredImage {
		...MediaParts
	}
	link
	slug
	segment
	socialImage {
		...MediaParts
	}
	seoTitle
	socialDescription
	socialTitle
	subject
	title
	authors: coAuthors {
		nodes {
			...AuthorParts
		}
	}
}
