fragment EmailParts on Email {
	id
	blocks {
		...BlockParts
	}
	dateGmt
	emailId
	featuredImage {
		...MediaParts
	}
	segment
	socialImage {
		...MediaParts
	}
	seoTitle
	socialDescription
	subject
	title
}
