fragment GuideParts on Guide {
	id
	guideId
	hasEssentials
	link
	count
	description
	shortDescription
	name
	slug
	featuredImage {
		...MediaParts
	}
	socialImage {
		...MediaParts
	}
	socialTitle
	colors
	headerImages {
		layer
		size
		image {
			...MediaParts
		}
	}
}
