fragment NugParts on Nug {
	id
	blocks {
		...BlockParts
		connections {
			... on Post {
				...ArticleTeaserParts
			}
			... on MediaItem {
				...MediaParts
			}
		}
	}
	dateGmt
	emailLists {
		nodes {
			emailListId
			slug
			listId
			name
		}
	}
	link
	modifiedGmt
	nugId
	slug
	title
	tags {
		nodes {
			id
			name
			slug
		}
	}
	topics {
		nodes {
			id
			name
			slug
		}
	}
}
