query Guides(
	$before: String = ""
	$perPage: Int = 10
) {
	guides(
		before: $before
		last: $perPage
		where: {
			orderby: TERM_ID
		}
	) {
		nodes {
			...GuideParts
			posts(
				last: 1
			) {
				nodes {
					id
					dateGmt
				}
			}
		}
		pageInfo {
			hasPreviousPage
			startCursor
		}
	}
}
