query Guides(
	$before: String = "",
	$perPage: Int = 10,
	$postsPerGuide: Int = 1
) {
	guides(
		before: $before,
		last: $perPage,
		where: {
			orderby: TERM_ID
		}
	) {
		nodes {
			...GuideParts
			posts(last: $postsPerGuide) {
				nodes {
					...ArticleTeaserParts
				}
			}
		}
		pageInfo {
			hasPreviousPage
			startCursor
		}
	}
}
