query GuidesByTopic(
	$perPage: Int = 50
	$slug: [String]!
) {
	topics(
		where: {
			slug: $slug
		}
	) {
		nodes {
			id
			name
			slug
			guides(
				last: $perPage,
				where: { orderby: TERM_ORDER }
			) {
				nodes {
					...GuideParts
				}
			}
		}
	}
}
