query PromotionsByTag(
	$perPage: Int!
	$slug: [String]!
) {
	promotions(
		first: $perPage
		where: {
			tagSlugIn: $slug
		}
	) {
		nodes {
			...PromotionParts
			blocks {
				...BlockParts
			}
		}
	}
}
