query Article(
	$id: Int!,
	$previewTime: Int,
	$previewToken: String,
) {
	posts(
		where: {
			id: $id
			preview: {
				time: $previewTime
				token: $previewToken
			}
		}
	) {
		nodes {
			...ArticleParts
		}
	}
}
