query ArticlesByTag(
	$after: String = "",
	$perPage: Int,
	$slug: String!
) {
	posts(
		where: { tagSlugIn: [$slug] },
		first: $perPage,
		after: $after
	) {
		nodes {
			...ArticleTeaserParts
		}
		pageInfo {
			endCursor
			hasNextPage
		}
	}
	tags(
		where: { slug: [$slug] }
	) {
		nodes {
			...TagParts
		}
	}
}
