query ArticlesByTag(
	$after: String = ""
	$perPage: Int
	$slug: [String]
) {
	tags(
		where: {
			slug: $slug
		}
	) {
		nodes {
			...TagParts
			posts(
				after: $after
				first: $perPage
			) {
				edges {
					node {
						...ArticleTeaserParts
					}
				}
				pageInfo {
					endCursor
					hasNextPage
				}
			}
		}
	}
}
