query ContentByTag(
	$slug: String!
	$perPage: Int = 10
	$after: String
) {
	tags(
		where: {
			slug: [$slug]
		}
	) {
		nodes {
			...TagParts
		}
	}
	tagContent(
		after: $after
		first: $perPage
		where: {
			slug: $slug
		}
	) {
		nodes {
			...on Email {
				...EmailParts
				emailLists {
					nodes {
						slug
					}
				}
			}
			...on Post {
				...ArticleTeaserParts
			}
		}
		pageInfo {
			endCursor
			hasNextPage
		}
	}
}
