query ContentByAuthor(
	$slug: String!
	$perPage: Int! = 10
	$after: String = ""
) {
	authors:coAuthors(
		where: {
			name: [$slug]
		}
	) {
		 nodes {
			...AuthorParts
		}
	}
	authorContent(
		after: $after
		first: $perPage
		where: {
			slug: $slug
		}
	) {
		nodes {
			...on Email {
				...EmailParts
			}
			...on Post {
				...ArticleTeaserParts
			}
		}
		pageInfo {
			endCursor
			hasNextPage
		}
	}
}