query FirstFeedConcentByRecency(
	$first: Int
) {
	feedContent( first: $first ) @connection(key: "FirstFeedConcentByRecency") {
		nodes {
			...on Post {
				...ArticleTeaserParts
			}
			...on Email {
				...EmailTeaserParts
				link
				emailLists {
					nodes {
						slug
					}
				}
			}
		}
		pageInfo {
			endCursor
		}
	}
}