query FirstPopularArticles(
	$edition: EditionName
	$first: Int
) {
	posts(
		first: $first
		where: {
			popular: {
				edition: $edition
			}
		}
	) {
		nodes {
			...ArticleTeaserParts
		}
		pageInfo {
			endCursor
			hasNextPage
		}
	}
}
