query LatestFeedContent(
	$after: String = ""
	$perPage: Int
) {
	feedContent( after: $after, first: $perPage ) {
		nodes {
			...on Post {
				...ArticleTeaserParts
			}
			...on Email {
				...EmailTeaserParts
				link
				emailLists {
					nodes {
						slug
					}
				}
			}
		}
		pageInfo {
			endCursor
		}
	}
}