name: Type Generation

on:
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    name: Generate & verify iOS Swift types
    runs-on: macOS-latest
    outputs:
      sha: ${{ steps.git_commit.outputs.sha }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: |
            .build/
            iOS/Codegen/.build/
          key: ${{ runner.os }}-${{ hashFiles('./Package.swift') }}

      - run: cd iOS/Codegen

      - name: Generate Swift types
        run: |
          swift build
          ./.build/debug/Codegen

      - run: cd ../../

      - name: Verify client package can be built
        run: swift build

      - name: Commit build files
        continue-on-error: true
        id: git_commit
        uses: zwaldowski/git-commit-action@v1
        with:
          commit_message: Add Swift types

      - continue-on-error: true
        run: git push

      - uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.git_commit.outputs.sha }}
          state: success
          context: Built Swift types
