name: Type Generation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-ios:
    name: Generate & verify iOS Swift types
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Switch to Xcode 12
        run: ls /Applications; sudo xcode-select -s /Applications/Xcode_12.4.app

      - name: Cache build
        uses: actions/cache@v2
        env:
          cache-name: cache-swift-packages
        with:
          path: |
            .build
            iOS/Codegen/.build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Generate Swift types
        run: |
          cd iOS/Codegen
          swift build
          ./.build/debug/Codegen

      - name: Verify client package can be built
        run: swift build

      - name: Commit build files
        continue-on-error: true
        id: git_commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all iOS Package.* Schemas
          git commit -m "Add Swift types" --no-verify --allow-empty
          SHA_OUTPUT=`git rev-parse HEAD`
          echo "::set-output name=sha::"$SHA_OUTPUT""
          git push

      - continue-on-error: true
        run: git push

      - uses: Sibz/github-status-action@v1
        continue-on-error: true
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.git_commit.outputs.sha }}
          state: success
          context: Built Swift types

  build-ts:
    name: Generate & verify TypeScript types
    needs: build-ios # we can’t run in parallel because `build-ios` downloads the schema and this job uses that schema file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - run: npm i

      - run: npm run build

      - name: Commit build files
        continue-on-error: true
        id: git_commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all Web
          git commit -m "Add TypeScript types" --no-verify --allow-empty
          SHA_OUTPUT=`git rev-parse HEAD`
          echo "::set-output name=sha::"$SHA_OUTPUT""
          git push

      - uses: Sibz/github-status-action@v1
        continue-on-error: true
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.git_commit.outputs.sha }}
          state: success
          context: Built TypeScript & Swift types
